CoreMVCDemo/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CoreMVCDemo.Models;
using MySql.Data.MySqlClient;
using Microsoft.Extensions.Configuration;
using CoreMVCDemo.Logics;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreMVCDemo.Controllers
{
    public class AdminDashboardController : Controller
    {
        public AdminDashboardService _objAdminDashboardService;
        bool _objStatusSignUpData;
        SignUpService _objLoginService;
        public AdminDashboardController()
        {
            _objAdminDashboardService = new AdminDashboardService();
            _objLoginService = new SignUpService();
        }
        public IActionResult Index(int? userId)
        {
            TempData["userId"] = userId;
            return  View();
        }
        public IActionResult ViewAllEnrolledStudents(int? userId)
        {
            TempData["userId"] = userId;
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return View(_objAdminDashboardService.GetAllEnrolledStudents(context));
        }
        public IActionResult ViewAllAppliedScholarships(int? userId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return View(_objAdminDashboardService.GetAllScholarshipsStatus(context, userId));
        }

        public IActionResult ApproveRejectScholarships(AdminUpdateScholarShipStatusViewModel _objStatusUpdateData)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return Json(_objAdminDashboardService.UpdateScholarshipsStatus(context, _objStatusUpdateData));
        }
        public IActionResult AddAdminAccount(int? userId)
        {
            TempData["userId"] = userId;
            SignUpViewModel modelData = new SignUpViewModel();
            IEnumerable<GenderType> GenderType = Enum.GetValues(typeof(GenderType))
                                                       .Cast<GenderType>();
            modelData.GenderList = from gender in GenderType
                                   select new SelectListItem
                                   {
                                       Text = gender.ToString(),
                                       Value = ((int)gender).ToString()
                                   };
            return View(modelData);
        }

        [HttpPost]
        public IActionResult SignUpAdminUser(SignUpViewModel _objSignUpViewModel)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            _objSignUpViewModel.IsAdmin = 1;
            _objStatusSignUpData = _objLoginService.SignUpUserService(context, _objSignUpViewModel);
            if (_objStatusSignUpData)
            {
                return Json("User Data saved succesfully.");
            }
            else
            {
                return Json("Username already Exist! Please try again with another username.");
            }
        }
    }
}

CoreMVCDemo/Views/AdminDashboard/AddAdminAccount.cshtml
@model CoreMVCDemo.Models.SignUpViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Admin Account Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.Partial("_AdminMenu.cshtml", TempData["userId"].ToString())
</div>
<h1>Welcome to Humber, Add Admin Account Page!</h1>
<div class="container col-lg-12">

    @using (Html.BeginForm("SignUpAdminUser", "AdminDashboard", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal padding10">
            <h4></h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                <div class="row col-md-12">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { id = "txtFullName", placeholder = "Enter Full Name", @class = "col-md-10 form-control", required = "required" } })
                    <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                <div class="row col-md-12">
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { id = "txtAge", placeholder = "Enter Age", @class = "col-md-10 form-control", required = "required" } })
                    <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GenderId, htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                <div class="row col-md-12">
                    @Html.DropDownListFor(model => model.GenderId, Model.GenderList, "Please select gender", new { @class = "col-md-10 form-control", required = "required" })
                    <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
                    @Html.ValidationMessageFor(model => model.GenderId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                <div class="row col-md-12">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { id = "txtUserName", placeholder = "Enter Username/Email here", @class = "col-md-10 form-control", required = "required" } })
                    <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                <div class="row col-md-12">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { id = "txtPasswdName", placeholder = "Enter Password here", @class = "col-md-10 form-control", required = "required" } })
                    <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                <div class="row col-md-12">
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { id = "txtConfirmPasswdName", placeholder = "Please Confirmed Password here", @class = "col-md-10 form-control", required = "required" } })
                    <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" id="signUpUserBtn" value="Create Account" class="btn btn-custom-save btn-danger" />
                </div>
            </div>
        </div>
    }

</div>

<script>
    var signUpUserUrl = '@Url.Action("AdminDashboard", "SignUpAdminUser")';
    $(document).ready(function () {
        $(".helpLink").click(function () {
            $(event.currentTarget.parentElement).find('[data-toggle="tooltip"]').tooltip();
        });
        function courseSelected(courseFee) {
            $("#txtCourseFee").val(courseFee);
        }
        $("form").on('submit', function () {
            event.preventDefault();
            // TODO do something here to show user that form is being submitted
            fetch(event.target.action, {
                method: 'POST',
                body: new URLSearchParams(new FormData(event.target)) // event.target is the form
            }).then((resp) => {
                console.log(resp);
                return resp.json(); // or resp.text() or whatever the server sends
            }).then((body) => {
                // TODO handle body
                console.log(body);
                if (body == "User data already Exist! Please try again with another username.") {
                    toastr.warning("Warning: " + result);
                }
                else {
                    $("#txtFullName,#txtAge, #txtGender, #txtUserName, #txtPasswdName, #txtConfirmPasswdName").val('');
                    toastr.success('Successfully added new admin user.');
                }
                $("#divLoading").hide();
            }).catch((error) => {
                // TODO handle error
                console.log(error);
                $("#divLoading").hide();

            });
            $("#divLoading").show();
        });
    });
</script>

CoreMVCDemo/Views/AdminDashboard/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Admin Dashboard Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>
    Admin Dashboard, View All Humber students!
</h1>
<div>
    @Html.Partial("_AdminMenu.cshtml", TempData["userId"].ToString())
</div>
<div>
    <label>Welcome to Humber College portal for the upcoming January 2022 intake.
    Important COVID-19 Humber Updates: Please take vaccination before accessing the Humber campus,
    Make sure you have downloaded Humber Guardian app in your phone and upload self-assessment status
    before visiting us. Thank you!!</label>
</div>

CoreMVCDemo/Views/AdminDashboard/ViewAllAppliedScholarships.cshtml
@model IEnumerable<CoreMVCDemo.Models.GetScholarShipStatusViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "View All Scholarships Status Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.Partial("_AdminMenu.cshtml", Model.FirstOrDefault().user_Id.ToString())
</div>
<h1>View All Applied Scholarships</h1>
<table class="table">
    <tr>
        <th>Select</th>
        <th>Name</th>
        <th>Mobile</th>
        <th>Email</th>
        <th>Course</th>
        <th>Registered Date</th>
        <th>Course Fee</th>
        <th>Amount</th>
        <th>Scholarship Name</th>
        <th>Scholarship Status</th>
        <th>Scholarship Award</th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        @if(item.scholarship_status == 1){
        <td>
            @Html.CheckBox("selStatusId", htmlAttributes: new { value = item.status_id, @checked = true }) @*, @onchange = "checkBoxChanged(this.value)"*@
        </td>
            }
        else{
    <td>
        @Html.CheckBox("selStatusId", htmlAttributes: new { value = item.status_id }) @*, @onchange = "checkBoxChanged(this.value)"*@
    </td>
        }
        <td>
            @Html.DisplayFor(modelItem => item.stu_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stu_mob)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stu_email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stu_course)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.reg_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.course_fee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.scholarship_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.scholarship_status_string)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ScholarshipAward)
        </td>
    </tr>
    }
</table>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" id="approveRejectScholarShipBtnClick" value="Approve/Reject Scholarship" class="btn btn-custom-save btn-danger" />
    </div>
</div>
<div class="modal fade" id="updateScholarshipsStatusConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title col-lg-10"><b>Approve/Reject Students Scholarships</b></h4>
                <button type="button" id="btnCourseModalClose" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" style="min-height:155px;">
                <div class="container-fluid form-horizontal">
                    <div class="row col-lg-12">
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-12 col-md-offset-1">
                                    @Html.Label(null, "Are you sure you want to approve checked scholarships and disapprove unchecked scholarships?", htmlAttributes: new { @class = "bold-strong control-label col-md-10" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12" style="text-align: center;">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a id="updateStatuScholarshipConfirmBtnClick" class="btn btn-danger btn-ok">Approve/Reject Scholarships</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var approveRejectScholarshipsStatusUrl = '@Url.Action("ApproveRejectScholarships", "AdminDashboard")';
    $(document).ready(function () {
        //$("#selStatusId:checked").attr('checked', false);
        $("#approveRejectScholarShipBtnClick").click(function () {
            if ($("#selStatusId:checked").val() > 0) {
                $("#updateScholarshipsStatusConfirmationModal").modal('show');
            } else {
                toastr.warning('Please select course and scholarship to continue!');
            }
        });
        $("#updateStatuScholarshipConfirmBtnClick").click(function () {
            var approvedStatus = $("input[name='selStatusId']:checkbox:checked");
            var rejectedStatus = $("input[name='selStatusId']:checkbox:not(:checked)");
            if (approvedStatus.length > 0 || rejectedStatus.length > 0 ) {
                $("#divLoading").show();
                var statusData = {}
                statusData.ApprovedStatusIds = [];
                statusData.RejectedStatusIds = [];
                for (i = 0; i < approvedStatus.length; i++) {
                    statusData.ApprovedStatusIds[i] = $(approvedStatus[i]).val();
                }
                for (j = 0; j < rejectedStatus.length; j++) {
                    statusData.RejectedStatusIds[j] = $(rejectedStatus[j]).val();
                }
                $.ajax({
                    url: approveRejectScholarshipsStatusUrl,
                    type: 'POST',
                    data: { _objStatusUpdateData: statusData },
                    success: function (result) {
                        if (result == null) {
                            toastr.warning("Warning: " + "Selected Course Id is invalid. Course Id does not exist. Please try again!");
                            $("#divLoading").hide();
                        }
                        else if (result) {
                            $("#updateScholarshipsStatusConfirmationModal").modal('hide');
                            toastr.success("Scholarship Applied successfully");
                            location.reload();
                            $("#divLoading").hide();
                        }
                    },
                    error: function (request, error) {
                        toastr.error("Error: " + JSON.stringify(request));
                        $("#divLoading").hide();
                    }
                });
            } else {
                toastr.warning('Please select valid course and scholarship to continue!');
            }
        });
    });
</script>

CoreMVCDemo/Views/AdminDashboard/ViewAllEnrolledStudents.cshtml
@model IEnumerable<CoreMVCDemo.Models.HumberStudentModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "View All Scholarships Status Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.Partial("_AdminMenu.cshtml", TempData["userId"].ToString())
</div>
<h1>Humber Students</h1>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Mobile</th>
        <th>Email</th>
        <th>Course</th>
        <th>Registered Date</th>
        <th>Course Fee</th>
        <th>Amount</th>
        <th>Created By</th>
        <th>IsActive</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayTextFor(modelItem => item.stu_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_mob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_course)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reg_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course_fee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created_by)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
        </tr>
    }
</table>

CoreMVCDemo/Views/AdminDashboard/_AdminMenu.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/AdminDashboard?userId=@Model">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/AdminDashboard/ViewAllEnrolledStudents?userId=@Model">View All Enrolled Students</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/AdminDashboard/ViewAllAppliedScholarships?userId=@Model">Approve/Reject Scholarships</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/AdminDashboard/AddAdminAccount?userId=@Model">Add Admin Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/Login/Index">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>