CoreMVCDemo/Controllers/StudentDashboardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CoreMVCDemo.Models;
using MySql.Data.MySqlClient;
using Microsoft.Extensions.Configuration;
using CoreMVCDemo.Logics;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreMVCDemo.Controllers
{
    public class StudentDashboardController : Controller
    {
        StudentDashboardService _objStudentDashboardService;
        List<CourseDetailsModel> _objCourseDetailsModels;
        public StudentDashboardController()
        {
            _objStudentDashboardService = new StudentDashboardService();
            _objCourseDetailsModels = new List<CourseDetailsModel>();
        }
        
        public IActionResult Index(int? userId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return View(_objStudentDashboardService.GetStudentMenuDetails(context, userId));
        }
        [HttpPost]
        public IActionResult AddCourse(CourseViewModel _objCourseViewModel)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return Json(_objStudentDashboardService.AddCourseService(context, _objCourseViewModel));
        }

        [HttpGet]
        public IActionResult SearchCourses(int? userId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return View(_objStudentDashboardService.GetStudentMenuDetails(context, userId));
        }

        [HttpPost]
        public IActionResult SearchRegisteredCourse(int? _courseId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return Json(_objStudentDashboardService.SearchCourseService(context, _courseId));
        }
        [HttpPost]
        public IActionResult EditCourse(CourseViewModel _objCourseViewModel)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return Json(_objStudentDashboardService.EditCourseService(context, _objCourseViewModel));
        }

        [HttpGet]
        public IActionResult ViewRegisteredCourses(int? userId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return View(_objStudentDashboardService.GetRegisteredCourses(context, userId));
        }
        [HttpPost]
        public IActionResult DeleteCourse(int? deleteCourseId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return Json(_objStudentDashboardService.DeleteCourseService(context, deleteCourseId));
        }

        [HttpGet]
        public IActionResult ApplyScholarships(int? userId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            ScholarShipSuperViewModel _objScholarShipSuperViewModel = new ScholarShipSuperViewModel();
            _objScholarShipSuperViewModel.AvailableScholarships = _objStudentDashboardService.GetListOfAvailableScholarships(context, userId);
            List<CourseDetailsModel> _objCourseDetailsModels = _objStudentDashboardService.GetAppliedCoursesDetailsService(context, userId);
            _objScholarShipSuperViewModel.SavedCourses = from course in _objCourseDetailsModels
                                                         select new SelectListItem
                                                         {
                                                             Text = course.course_name.ToString(),
                                                             Value = course.course_id.ToString()
                                                         };
            _objScholarShipSuperViewModel.userId = userId.ToString();
            return View(_objScholarShipSuperViewModel);
        }
        [HttpPost]
        public IActionResult UpdateScholarships(int? scholarShipId, int? courseId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            return Json(_objStudentDashboardService.ApplyScholarshipService(context, scholarShipId, courseId));
        }
        [HttpGet]
        public IActionResult ViewScholarshipsStatus(int? userId)
        {
            HumberDbContext context = HttpContext.RequestServices.GetService(typeof(CoreMVCDemo.Models.HumberDbContext)) as HumberDbContext;
            List<GetScholarShipStatusViewModel> _objGetScholarShipStatusViewModel = _objStudentDashboardService.GetScholarShipStatus(context, userId);
            _objGetScholarShipStatusViewModel.FirstOrDefault().user_Id = (int)userId;
            return View(_objGetScholarShipStatusViewModel);
        }
    }
}

CoreMVCDemo/Views/StudentDashboard/ApplyScholarships.cshtml
@model CoreMVCDemo.Models.ScholarShipSuperViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Apply Scholarships Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.Partial("_StudentMenu.cshtml", Model.userId)
</div>
<h1>Apply Scholarships for the Registered Courses</h1>
<br />
<h4>Please select scholarship</h4>
<table class="table">
    <tr>
        <th>Select</th>
        <th>Name</th>
        <th>Award</th>
    </tr>
    @foreach (var item in Model.AvailableScholarships)
    {
        <tr>
            <td>
                @Html.RadioButtonFor(model => item.scholarship_id, item.scholarship_id, new { id = "selScholarshipId" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.scholarship_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.award)
            </td>
        </tr>
    }
</table>

<h4>Please choose any course</h4>
<div class="form-group">
    <div class="row col-md-12">
        @Html.DropDownListFor(model => model.SavedCourses, Model.SavedCourses, "Please select course", new { id = "txtSavedCourses", @class = "col-md-10 form-control", required = "required" })
        <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
        @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" id="applyScholarShipBtnClick" value="Apply Scholarship" class="btn btn-custom-save btn-danger" />
    </div>
</div>
<div class="modal fade" id="applyScholarshipConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title col-lg-7"><b>Apply Scholarship</b></h4>
                <button type="button" id="btnCourseModalClose" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" style="min-height:155px;">
                <div class="container-fluid form-horizontal">
                    <div class="row col-lg-12">
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-12 col-md-offset-1">
                                    @Html.Label(null, "Are you sure you want to apply scholarship for the selected course?", htmlAttributes: new { @class = "bold-strong control-label col-md-10" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12" style="text-align: center;">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a id="scholarshipConfirmBtnClick" class="btn btn-danger btn-ok">Apply Scholarship</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var updateScholarshipUrl = '@Url.Action("UpdateScholarships", "StudentDashboard")';
    $(document).ready(function () {
        $("#selScholarshipId:checked").attr('checked', false);
        $("#applyScholarShipBtnClick").click(function () {
            if ($("#selScholarshipId:checked").val() > 0 && $("#txtSavedCourses").val() > 0) {
                $("#applyScholarshipConfirmationModal").modal('show');
            } else {
                toastr.warning('Please select course and scholarship to continue!');
            }
        });
        $("#scholarshipConfirmBtnClick").click(function () {
            if ($("#selScholarshipId:checked").val() > 0 && $("#txtSavedCourses").val() > 0) {
                $("#divLoading").show();
                $.ajax({
                    url: updateScholarshipUrl,
                    type: 'POST',
                    data: { scholarShipId: $("#selScholarshipId:checked").val(), courseId: $("#txtSavedCourses").val() },
                    success: function (result) {
                        if (result == null) {
                            toastr.warning("Warning: " + "Selected Course Id is invalid. Course Id does not exist. Please try again!");
                            $("#divLoading").hide();
                        }
                        else if (result) {
                            $("#applyScholarshipConfirmationModal").modal('hide');
                            toastr.success("Scholarship Applied successfully");
                            location.reload();
                            $("#divLoading").hide();
                        }
                    },
                    error: function (request, error) {
                        toastr.error("Error: " + JSON.stringify(request));
                        $("#divLoading").hide();
                    }
                });
            } else {
                toastr.warning('Please select course and scholarship to continue!');
            }
        });
    });
</script>

CoreMVCDemo/Views/StudentDashboard/Index.cshtml
@model CoreMVCDemo.Models.CourseViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Student Dashboard Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    var userId = '@Html.Raw(Json.Serialize(Model.created_by))';
    //var userId = 'Html.Raw(Json.Encode(Model.created_by))';
</script>

<div>
    @Html.Partial("_StudentMenu.cshtml", Model.created_by.ToString())
</div>
<div>
    @Html.Partial("_AddCourse.cshtml")
</div>

CoreMVCDemo/Views/StudentDashboard/SearchCourses.cshtml
@model CoreMVCDemo.Models.CourseViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Search Course Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.Partial("_StudentMenu.cshtml", Model.created_by.ToString())
</div>
<h1>Search Registered Course</h1>
<div class="container col-lg-12">
    <div class="form-horizontal padding10">
        <div class="form-group">
            @Html.Label(null, "Course Id", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
            <div class="row col-md-12">
                @Html.TextBox("txtCourseID", null, new { @class = "col-md-10 form-control", placeholder = "Enter Course Id", @maxlength = 255, @required = true })
                <i class="col-md-1 fa fa-lg fa-question-circle helpLink" data-toggle="tooltip" title="For more help please contact Humber IT Desk" hId="48" data-placement="bottom"></i>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="searchCourseBtn" value="Search Course" class="btn btn-custom-save btn-danger" />
            </div>
        </div>
    </div>
</div>


<!-- Modal for Save Course-->
<div class="modal fade" id="courseModal" data-backdrop="static" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title col-lg-7"><b>Course Details</b></h4>
                <button type="button" id="btnCourseModalClose" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" style="min-height:155px;">
                <div class="container-fluid form-horizontal">
                    <div class="row col-lg-12">
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-2 col-md-offset-1">
                                    @Html.Label(null, "Username/ Email", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                                </div>
                                <div class="col-md-8 col-md-offset-1">
                                    @Html.TextBox("txtStudentEmail", null, new { @class = "form-control", @maxlength = 255, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-2 col-md-offset-1">
                                    @Html.Label(null, "Student Name", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                                </div>
                                <div class="col-md-8 col-md-offset-1">
                                    @Html.TextBox("txtStudentName", null, new { @class = "form-control", @maxlength = 255, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-2 col-md-offset-1">
                                    @Html.Label(null, "Contact", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                                </div>
                                <div class="col-md-8 col-md-offset-1">
                                    @Html.TextBox("txtStudentMob", null, new { @class = "form-control", @maxlength = 255, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-2 col-md-offset-1">
                                    @Html.Label(null, "Course Name", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                                </div>
                                <div class="col-md-8 col-md-offset-1">
                                    @Html.TextBox("txtCourseName", null, new { @class = "form-control", @maxlength = 255, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-12">
                            <div class="row  row-margin">
                                <div class="col-md-2 col-md-offset-1">
                                    @Html.Label(null, "Course Fee", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                                </div>
                                <div class="col-md-8 col-md-offset-1">
                                    @Html.TextBox("txtCourseFee", null, new { @class = "form-control", @maxlength = 255, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-2 col-md-offset-1">
                                    @Html.Label(null, "Paid Amount", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                                </div>
                                <div class="col-md-8 col-md-offset-1">
                                    @Html.TextBox("txtAmount", null, new { @class = "form-control", @maxlength = 255 })
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-2 col-md-offset-1">
                                    @Html.Label(null, "Registered Date", htmlAttributes: new { @class = "bold-strong control-label col-md-2" })
                                </div>
                                <div class="col-md-8 col-md-offset-1">
                                    @Html.TextBox("txtRegDate", null, new { @class = "form-control", @maxlength = 255, @readonly = true })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12" style="text-align: center;">
                    <button type="button" id="btnSaveEditedCourse" class="btn btn-custom-save btn-danger">Save</button>
                    <button type="button" id="btnCancelSearch" class="btn btn-link" data-dismiss="modal" style="color: #17a2b8!important; outline: none;">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/studentDashboard.js" asp-append-version="true"></script>
<script>
    var searchRegisteredCourseUrl = '@Url.Action("SearchRegisteredCourse", "StudentDashboard")';
    var editCourseUrl = '@Url.Action("EditCourse", "StudentDashboard")';
    $(document).ready(function () {
        $("#searchCourseBtn").click(function () {
            if ($("#txtCourseID").val() !== '') {
                $("#divLoading").show();
                $.ajax({
                    url: searchRegisteredCourseUrl,
                    type: 'POST',
                    data: { _courseId: $("#txtCourseID").val() },
                    success: function (result) {
                        if (result == null) {
                            toastr.warning("Warning: " + "Entered Course Id is invalid. Course Id does not exist. Please try again!");
                            $("#divLoading").hide();
                        }
                        else {
                            $("#txtStudentName").val(result.stu_name);
                            $("#txtStudentEmail").val(result.stu_email);
                            $("#txtStudentMob").val(result.stu_mob);
                            $("#txtCourseName").val(result.stu_course);
                            $("#txtCourseFee").val(result.course_fee);
                            $("#txtAmount").val(result.amount);
                            $("#txtRegDate").val(result.reg_date);
                            $("#courseModal").modal('show');
                            toastr.success("Course Details fetched successfully");
                            $("#divLoading").hide();
                        }
                    },
                    error: function (request, error) {
                        toastr.error("Error: " + JSON.stringify(request));
                        $("#divLoading").hide();
                    }
                });
            } else {
                toastr.warning('Please provide course Id to search for!');
            }
        });
        $("#btnSaveEditedCourse").click(function () {
            if ($("#txtCourseID").val() !== '') {
                $("#divLoading").show();
                var _objCourseViewModel = {}
                _objCourseViewModel.stu_id = $("#txtCourseID").val();
                _objCourseViewModel.stu_name = $("#txtStudentName").val();
                _objCourseViewModel.stu_email = $("#txtStudentEmail").val();
                _objCourseViewModel.stu_mob = $("#txtStudentMob").val();
                _objCourseViewModel.stu_course = $("#txtCourseName").val();
                _objCourseViewModel.course_fee = $("#txtCourseFee").val();
                _objCourseViewModel.amount = $("#txtAmount").val();
                _objCourseViewModel.reg_date = $("#txtRegDate").val();

                $.ajax({
                    url: editCourseUrl,
                    type: 'POST',
                    data: { _objCourseViewModel: _objCourseViewModel },
                    success: function (result) {
                        if (result == null) {
                            toastr.warning("Warning: " + "Entered Course Id is invalid. Course Id does not exist. Please try again!");
                            $("#divLoading").hide();
                        }
                        else if (result) {
                            $("#courseModal").modal('hide');
                            toastr.success("Course updated successfully");
                            $("#divLoading").hide();
                        }
                    },
                    error: function (request, error) {
                        toastr.error("Error: " + JSON.stringify(request));
                        $("#divLoading").hide();
                    }
                });
            } else {
                toastr.warning('Please provide course Id to search for!');
            }
        });
    });
</script>

CoreMVCDemo/Views/StudentDashboard/ViewRegisteredCourses.cshtml
@model IEnumerable<CoreMVCDemo.Models.CourseViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "View Registered Courses Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.Partial("_StudentMenu.cshtml", Model.FirstOrDefault().created_by.ToString())
</div>
<h1>View Registered Courses</h1>
<table class="table">
    <tr>
        <th>Sel</th>
        <th>Name</th>
        <th>Mobile</th>
        <th>Email</th>
        <th>Course</th>
        <th>Registered Date</th>
        <th>Course Fee</th>
        <th>Amount</th>
        <th>Created By</th>
        <th>IsActive</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.RadioButtonFor(model => item.stu_id, item.stu_id, new { id = "selCourseId" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_mob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stu_course)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reg_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course_fee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created_by)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
        </tr>
    }
</table>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" id="deleteSavedCourseBtn" value="Delete Course" class="btn btn-custom-save btn-danger" />
    </div>
</div>

<div class="modal fade" id="deleteCourseConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title col-lg-7"><b>Delete Course</b></h4>
                <button type="button" id="btnCourseModalClose" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" style="min-height:155px;">
                <div class="container-fluid form-horizontal">
                    <div class="row col-lg-12">
                        <div class="form-group col-lg-12">
                            <div class="row row-margin">
                                <div class="col-md-11 col-md-offset-1">
                                    @Html.Label(null, "Are you sure to delete the selected registered course?", htmlAttributes: new { @class = "bold-strong control-label col-md-10" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12" style="text-align: center;">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a id="delConfirmBtnClick" class="btn btn-danger btn-ok">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var deleteCourseUrl = '@Url.Action("DeleteCourse", "StudentDashboard")';
    $(document).ready(function () {
        $("#selCourseId:checked").attr('checked', false);
        $("#deleteSavedCourseBtn").click(function () {
            $("#deleteCourseConfirmationModal").modal('show');
        });
        $("#delConfirmBtnClick").click(function () {
            if ($("#selCourseId:checked").val() > 0) {
                $("#divLoading").show();
                $.ajax({
                    url: deleteCourseUrl,
                    type: 'POST',
                    data: { deleteCourseId: $("#selCourseId:checked").val() },
                    success: function (result) {
                        if (result == null) {
                            toastr.warning("Warning: " + "Selected Course Id is invalid. Course Id does not exist. Please try again!");
                            $("#divLoading").hide();
                        }
                        else if (result) {
                            $("#deleteCourseConfirmationModal").modal('hide');
                            toastr.success("Course deleted successfully");
                            location.reload();
                            $("#divLoading").hide();
                        }
                    },
                    error: function (request, error) {
                        toastr.error("Error: " + JSON.stringify(request));
                        $("#divLoading").hide();
                    }
                });
            } else {
                toastr.warning('Please select course to delete for!');
            }
        });
    });
</script>

CoreMVCDemo/Views/StudentDashboard/ViewScholarshipsStatus.cshtml
@model IEnumerable<CoreMVCDemo.Models.GetScholarShipStatusViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "View Scholarships Status Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.Partial("_StudentMenu.cshtml", Model.FirstOrDefault().user_Id.ToString())
</div>
<h1>View Registered Courses</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Mobile</th>
        <th>Email</th>
        <th>Course</th>
        <th>Registered Date</th>
        <th>Course Fee</th>
        <th>Amount</th>
        <th>Scholarship Name</th>
        <th>Scholarship Status</th>
        <th>Scholarship Award</th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.stu_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stu_mob)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stu_email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stu_course)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.reg_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.course_fee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.scholarship_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.scholarship_status_string)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ScholarshipAward)
        </td>
    </tr>
    }
</table>

CoreMVCDemo/Views/StudentDashboard/_StudentMenu.cshtml
@model string

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/StudentDashboard?userId=@Model">Add Course</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/StudentDashboard/SearchCourses?userId=@Model">Search Saved Course</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/StudentDashboard/ViewRegisteredCourses?userId=@Model">View Registered Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/StudentDashboard/ApplyScholarships?userId=@Model">Apply Scholarships</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/StudentDashboard/ViewScholarshipsStatus?userId=@Model">View Scholarships Status</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/Login/Index">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>